<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620220602 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trick (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE trick_classification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, grade VARCHAR(1) NOT NULL, level INT NOT NULL, family VARCHAR(255) NOT NULL, trick_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_906C7A7FB281BE2E ON trick_classification (trick_id)');
        $this->addSql('ALTER TABLE trick_classification ADD CONSTRAINT FK_906C7A7FB281BE2E FOREIGN KEY (trick_id) REFERENCES trick (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_judge_execution_score');
        $this->addSql('ALTER TABLE run_execution ADD trick_id INT NOT NULL');
        $this->addSql('ALTER TABLE run_execution DROP trick_name');
        $this->addSql('ALTER TABLE run_execution ADD CONSTRAINT FK_C721DAC6B281BE2E FOREIGN KEY (trick_id) REFERENCES trick (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C721DAC6B281BE2E ON run_execution (trick_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trick_classification DROP CONSTRAINT FK_906C7A7FB281BE2E');
        $this->addSql('DROP TABLE trick');
        $this->addSql('DROP TABLE trick_classification');
        $this->addSql('CREATE UNIQUE INDEX uniq_judge_execution_score ON judge_score (judge_id, run_execution_id)');
        $this->addSql('ALTER TABLE run_execution DROP CONSTRAINT FK_C721DAC6B281BE2E');
        $this->addSql('DROP INDEX IDX_C721DAC6B281BE2E');
        $this->addSql('ALTER TABLE run_execution ADD trick_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE run_execution DROP trick_id');
    }
}
