<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620173942 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE judge_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, judge_id INT NOT NULL, run_execution_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2D051AAB7D66194 ON judge_score (judge_id)');
        $this->addSql('CREATE INDEX IDX_C2D051AAC4DD12CE ON judge_score (run_execution_id)');
        $this->addSql('ALTER TABLE judge_score ADD CONSTRAINT FK_C2D051AAB7D66194 FOREIGN KEY (judge_id) REFERENCES judge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE judge_score ADD CONSTRAINT FK_C2D051AAC4DD12CE FOREIGN KEY (run_execution_id) REFERENCES run_execution (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_JUDGE_EXECUTION_SCORE ON judge_score (judge_id, run_execution_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_JUDGE_EXECUTION_SCORE');
        $this->addSql('ALTER TABLE judge_score DROP CONSTRAINT FK_C2D051AAB7D66194');
        $this->addSql('ALTER TABLE judge_score DROP CONSTRAINT FK_C2D051AAC4DD12CE');
        $this->addSql('DROP TABLE judge_score');
    }
}
