<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620173019 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tournament_id INT NOT NULL, skater_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5076A4C033D1A3E7 ON run (tournament_id)');
        $this->addSql('CREATE INDEX IDX_5076A4C01630D3DD ON run (skater_id)');
        $this->addSql('CREATE TABLE run_execution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trick_name VARCHAR(255) NOT NULL, sequence_number INT NOT NULL, line INT NOT NULL, run_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C721DAC684E3FEC4 ON run_execution (run_id)');
        $this->addSql('CREATE TABLE skater (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE run ADD CONSTRAINT FK_5076A4C033D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE run ADD CONSTRAINT FK_5076A4C01630D3DD FOREIGN KEY (skater_id) REFERENCES skater (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE run_execution ADD CONSTRAINT FK_C721DAC684E3FEC4 FOREIGN KEY (run_id) REFERENCES run (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE run DROP CONSTRAINT FK_5076A4C033D1A3E7');
        $this->addSql('ALTER TABLE run DROP CONSTRAINT FK_5076A4C01630D3DD');
        $this->addSql('ALTER TABLE run_execution DROP CONSTRAINT FK_C721DAC684E3FEC4');
        $this->addSql('DROP TABLE run');
        $this->addSql('DROP TABLE run_execution');
        $this->addSql('DROP TABLE skater');
    }
}
